FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y --force-yes build-essential curl wget tar git perl gcc make sqlite3 postgresql
RUN apt-get install -y --force-yes zlib1g-dev libssl-dev libreadline-dev libyaml-dev libxml2-dev libxslt-dev

USER ubuntu:ubuntu
WORKDIR /home/ubuntu

RUN mkdir .rbenv
RUN mkdir .nvm

COPY ruby.sh /home/ubuntu/ruby.sh
COPY node.sh /home/ubuntu/node.sh

COPY project.sh /home/ubuntu/project.sh